### PR TITLE
More words added on Spanish

### PR DESCRIPTION
**Pull request by juanpintom**

### CODE REVIEW

**Comment by shineangelic** [comment]
thank you juan. Did you manage to have the second scenario working? Or is
it a bug?

Alessandro

2015-10-19 17:28 GMT+02:00 juanpintom notifications@github.com:

**Comment by juanpintom** [comment]
Yes (I think),

I have 4 scenes, the default ones and two mine, when I say "Ocio Encendido"
it works well, but if I say "Ocio Apagado" on the feedback I see "ocio
apagado: comand not recognized"  I tried to delete both and created again
and now it works so I can't reproduce the problem.

I'll create more scenes and try again. Other commands works very well

Regards

2015-10-19 19:21 GMT+02:00 Alessandro Del Pex notifications@github.com:

**Comment by shineangelic** [comment]
if you can't solve it please open an issue, thanks

**Comment by juanpintom** [comment]
Ok Thanks ;)

2015-10-19 22:37 GMT+02:00 Alessandro Del Pex notifications@github.com:

**Pull request merged**
